# SPDX-License-Identifier: Apache-2.0
"""Curated Studio analysis/cutting presets.

Presets intentionally contain only creative/editing controls. They do not choose
hardware devices, credentials, models, or enable paid AI features. Studio applies
one preset visibly to the existing controls, after which every value remains
individually editable.
"""
from __future__ import annotations

from copy import deepcopy
from typing import Any


ANALYSIS_PRESETS: dict[str, dict[str, Any]] = {
    "balanced": {
        "label": "Balanced",
        "description": "General-purpose musical edit with moderate motion, layering, variety, and phrase-aware pacing.",
        "parameters": {
            "section_bars": 8,
            "max_video_layers": 3,
            "transform_intensity": 1.20,
            "creative_intensity": 1.00,
            "effect_density": 1.25,
            "temporal_persistence": 1.15,
            "composition_diversity": 1.15,
            "hero_frequency": 1.15,
            "composition_intensity": 1.20,
            "target_unique_clips": 0,
            "novelty_weight": 0.65,
            "visual_match_weight": 1.25,
            "transition_weight": 0.70,
            "trajectory_strength": 0.85,
            "anticipation_seconds": 12.0,
            "sequence_lookahead": 5,
            "sequence_beam_width": 6,
            "effect_compatibility_weight": 0.60,
            "preference_weight": 0.35,
            "vector_intensity": 1.00,
            "codec_glitch": "off",
            "codec_glitch_intensity": 0.65,
            "min_shot_seconds": 0.65,
            "max_shot_seconds": 6.0,
            "source_excerpt_max_seconds": 5.0,
            "audio_visual_match_weight": 1.10,
            "audio_ai_window": 8.0,
            "audio_ai_hop": 4.0,
            "choreography": True,
            "dynamic_shots": True,
            "rhythm_alignment": True,
            "creative_effects": True,
            "vector_effects": True,
        },
    },
    "high-energy": {
        "label": "High Energy",
        "description": "Fast, punchy cutting with strong build/drop response, short excerpts, more novelty, and assertive motion effects.",
        "parameters": {
            "section_bars": 4,
            "max_video_layers": 3,
            "transform_intensity": 1.50,
            "creative_intensity": 1.40,
            "effect_density": 1.80,
            "temporal_persistence": 1.35,
            "composition_diversity": 1.55,
            "hero_frequency": 1.65,
            "composition_intensity": 1.30,
            "target_unique_clips": 0,
            "novelty_weight": 0.90,
            "visual_match_weight": 1.35,
            "transition_weight": 0.50,
            "trajectory_strength": 1.20,
            "anticipation_seconds": 8.0,
            "sequence_lookahead": 5,
            "sequence_beam_width": 7,
            "effect_compatibility_weight": 0.75,
            "preference_weight": 0.30,
            "vector_intensity": 1.30,
            "codec_glitch": "off",
            "codec_glitch_intensity": 0.65,
            "min_shot_seconds": 0.35,
            "max_shot_seconds": 2.75,
            "source_excerpt_max_seconds": 2.50,
            "audio_visual_match_weight": 1.25,
            "audio_ai_window": 6.0,
            "audio_ai_hop": 2.0,
            "choreography": True,
            "dynamic_shots": True,
            "rhythm_alignment": True,
            "creative_effects": True,
            "vector_effects": True,
        },
    },
    "edm": {
        "label": "EDM",
        "description": "Beat-forward club/festival pacing with deliberate build anticipation, strong drop payoffs, rhythmic source motion, and layered effects.",
        "parameters": {
            "section_bars": 8,
            "max_video_layers": 3,
            "transform_intensity": 1.45,
            "creative_intensity": 1.35,
            "effect_density": 1.70,
            "temporal_persistence": 1.50,
            "composition_diversity": 1.50,
            "hero_frequency": 1.60,
            "composition_intensity": 1.30,
            "target_unique_clips": 0,
            "novelty_weight": 0.75,
            "visual_match_weight": 1.45,
            "transition_weight": 0.72,
            "trajectory_strength": 1.30,
            "anticipation_seconds": 16.0,
            "sequence_lookahead": 6,
            "sequence_beam_width": 8,
            "effect_compatibility_weight": 0.85,
            "preference_weight": 0.35,
            "vector_intensity": 1.25,
            "codec_glitch": "off",
            "codec_glitch_intensity": 0.55,
            "min_shot_seconds": 0.45,
            "max_shot_seconds": 4.0,
            "source_excerpt_max_seconds": 3.5,
            "audio_visual_match_weight": 1.35,
            "audio_ai_window": 8.0,
            "audio_ai_hop": 2.0,
            "choreography": True,
            "dynamic_shots": True,
            "rhythm_alignment": True,
            "creative_effects": True,
            "vector_effects": True,
        },
    },
    "relaxed": {
        "label": "Relaxed",
        "description": "Longer, smoother shots with restrained transforms, fewer layers, strong continuity, and gentle phrase evolution.",
        "parameters": {
            "section_bars": 16,
            "max_video_layers": 2,
            "transform_intensity": 0.45,
            "creative_intensity": 0.55,
            "effect_density": 0.60,
            "temporal_persistence": 0.75,
            "composition_diversity": 0.55,
            "hero_frequency": 0.45,
            "composition_intensity": 0.35,
            "target_unique_clips": 0,
            "novelty_weight": 0.35,
            "visual_match_weight": 1.15,
            "transition_weight": 1.10,
            "trajectory_strength": 0.45,
            "anticipation_seconds": 18.0,
            "sequence_lookahead": 7,
            "sequence_beam_width": 7,
            "effect_compatibility_weight": 0.70,
            "preference_weight": 0.40,
            "vector_intensity": 0.30,
            "codec_glitch": "off",
            "codec_glitch_intensity": 0.35,
            "min_shot_seconds": 1.75,
            "max_shot_seconds": 9.0,
            "source_excerpt_max_seconds": 8.0,
            "audio_visual_match_weight": 0.95,
            "audio_ai_window": 12.0,
            "audio_ai_hop": 6.0,
            "choreography": True,
            "dynamic_shots": True,
            "rhythm_alignment": True,
            "creative_effects": True,
            "vector_effects": True,
        },
    },
    "vibrant": {
        "label": "Vibrant",
        "description": "Colorful, varied, visually rich editing that favors expressive footage and creative treatment without becoming hyperactive.",
        "parameters": {
            "section_bars": 8,
            "max_video_layers": 3,
            "transform_intensity": 1.10,
            "creative_intensity": 1.45,
            "effect_density": 1.55,
            "temporal_persistence": 1.15,
            "composition_diversity": 1.35,
            "hero_frequency": 1.25,
            "composition_intensity": 1.15,
            "target_unique_clips": 0,
            "novelty_weight": 0.95,
            "visual_match_weight": 1.55,
            "transition_weight": 0.62,
            "trajectory_strength": 0.90,
            "anticipation_seconds": 12.0,
            "sequence_lookahead": 5,
            "sequence_beam_width": 7,
            "effect_compatibility_weight": 0.75,
            "preference_weight": 0.35,
            "vector_intensity": 1.10,
            "codec_glitch": "off",
            "codec_glitch_intensity": 0.50,
            "min_shot_seconds": 0.70,
            "max_shot_seconds": 4.75,
            "source_excerpt_max_seconds": 4.25,
            "audio_visual_match_weight": 1.20,
            "audio_ai_window": 8.0,
            "audio_ai_hop": 3.0,
            "choreography": True,
            "dynamic_shots": True,
            "rhythm_alignment": True,
            "creative_effects": True,
            "vector_effects": True,
        },
    },
    "cinematic": {
        "label": "Cinematic",
        "description": "Intentional long-form edit with stronger continuity, deep lookahead, controlled layering, and pronounced whole-song visual arcs.",
        "parameters": {
            "section_bars": 8,
            "max_video_layers": 2,
            "transform_intensity": 0.75,
            "creative_intensity": 0.95,
            "effect_density": 0.85,
            "temporal_persistence": 1.10,
            "composition_diversity": 0.75,
            "hero_frequency": 0.70,
            "composition_intensity": 0.65,
            "target_unique_clips": 0,
            "novelty_weight": 0.50,
            "visual_match_weight": 1.45,
            "transition_weight": 1.20,
            "trajectory_strength": 1.05,
            "anticipation_seconds": 20.0,
            "sequence_lookahead": 8,
            "sequence_beam_width": 9,
            "effect_compatibility_weight": 0.90,
            "preference_weight": 0.40,
            "vector_intensity": 0.65,
            "codec_glitch": "off",
            "codec_glitch_intensity": 0.40,
            "min_shot_seconds": 1.25,
            "max_shot_seconds": 8.0,
            "source_excerpt_max_seconds": 7.0,
            "audio_visual_match_weight": 1.15,
            "audio_ai_window": 10.0,
            "audio_ai_hop": 4.0,
            "choreography": True,
            "dynamic_shots": True,
            "rhythm_alignment": True,
            "creative_effects": True,
            "vector_effects": True,
        },
    },
    "dreamy": {
        "label": "Dreamy / Atmospheric",
        "description": "Flowing, layered, temporal treatment with slower edits and continuity weighted above hard rhythmic cutting.",
        "parameters": {
            "section_bars": 16,
            "max_video_layers": 3,
            "transform_intensity": 0.95,
            "creative_intensity": 1.30,
            "effect_density": 1.30,
            "temporal_persistence": 1.75,
            "composition_diversity": 1.20,
            "hero_frequency": 0.90,
            "composition_intensity": 1.45,
            "target_unique_clips": 0,
            "novelty_weight": 0.60,
            "visual_match_weight": 1.30,
            "transition_weight": 1.15,
            "trajectory_strength": 0.65,
            "anticipation_seconds": 18.0,
            "sequence_lookahead": 7,
            "sequence_beam_width": 8,
            "effect_compatibility_weight": 0.85,
            "preference_weight": 0.35,
            "vector_intensity": 0.80,
            "codec_glitch": "off",
            "codec_glitch_intensity": 0.35,
            "min_shot_seconds": 1.20,
            "max_shot_seconds": 7.0,
            "source_excerpt_max_seconds": 6.0,
            "audio_visual_match_weight": 1.05,
            "audio_ai_window": 12.0,
            "audio_ai_hop": 4.0,
            "choreography": True,
            "dynamic_shots": True,
            "rhythm_alignment": True,
            "creative_effects": True,
            "vector_effects": True,
        },
    },
    "experimental": {
        "label": "Experimental / Glitch",
        "description": "Aggressive variation, dense compositing, short cuts, strong vector treatment, and musical codec-glitch scheduling for intentionally unstable visuals.",
        "parameters": {
            "section_bars": 4,
            "max_video_layers": 4,
            "transform_intensity": 1.85,
            "creative_intensity": 1.85,
            "effect_density": 2.25,
            "temporal_persistence": 1.90,
            "composition_diversity": 1.90,
            "hero_frequency": 2.10,
            "composition_intensity": 1.75,
            "target_unique_clips": 0,
            "novelty_weight": 1.25,
            "visual_match_weight": 0.95,
            "transition_weight": 0.30,
            "trajectory_strength": 1.15,
            "anticipation_seconds": 8.0,
            "sequence_lookahead": 4,
            "sequence_beam_width": 7,
            "effect_compatibility_weight": 0.45,
            "preference_weight": 0.20,
            "vector_intensity": 1.70,
            "codec_glitch": "musical",
            "codec_glitch_intensity": 0.95,
            "min_shot_seconds": 0.30,
            "max_shot_seconds": 2.50,
            "source_excerpt_max_seconds": 2.25,
            "audio_visual_match_weight": 1.00,
            "audio_ai_window": 6.0,
            "audio_ai_hop": 2.0,
            "choreography": True,
            "dynamic_shots": True,
            "rhythm_alignment": True,
            "creative_effects": True,
            "vector_effects": True,
        },
    },
}


def analysis_presets_payload() -> list[dict[str, Any]]:
    """Return the preset catalog in stable display order for Studio."""
    return [
        {"id": preset_id, **deepcopy(definition)}
        for preset_id, definition in ANALYSIS_PRESETS.items()
    ]


def apply_analysis_preset(options: dict[str, Any]) -> dict[str, Any]:
    """Merge an explicitly requested preset below caller-provided overrides.

    No preset is applied when ``analysis_preset`` is absent/empty/``custom`` so
    existing API clients keep their historical defaults.
    """
    result = dict(options)
    preset_id = str(result.get("analysis_preset") or "").strip()
    if not preset_id or preset_id == "custom":
        return result
    try:
        definition = ANALYSIS_PRESETS[preset_id]
    except KeyError as exc:
        choices = ", ".join(ANALYSIS_PRESETS)
        raise ValueError(f"unknown analysis preset {preset_id!r}; choose one of: {choices}") from exc
    merged = dict(definition["parameters"])
    merged.update(result)
    return merged
